config/routes.rb
Opentrak::Application.routes.draw do
  
  resources :access_tokens
  
  devise_for :users

  resources :trackers
  resources :tags
  
  match 'track/:name' => 'trackers#track', :as => 'track_tracker'
  
  match 'api' => "api#post", :via => :post
  

  root :to => "trackers#blocked"

end

app/models/access_token.rb
# == Schema Information
# Schema version: 20110701233142
#
# Table name: access_tokens
#
#  id          :integer         not null, primary key
#  user_id     :integer
#  token       :string(255)
#  active      :boolean
#  last_access :datetime
#  created_at  :datetime
#  updated_at  :datetime
#

class AccessToken < ActiveRecord::Base
  validates :user_id, :presence => true
  validates :token, :presence => true, :uniqueness => true
  belongs_to  :user
  
  def stamp_accessed
    update_attribute(:last_access, Time.now)
  end
  
end

app/controllers/access_tokens_controller.rb
class AccessTokensController < ApplicationController
  # GET /access_tokens
  # GET /access_tokens.xml
  def index
    @access_tokens = AccessToken.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @access_tokens }
    end
  end

  # GET /access_tokens/1
  # GET /access_tokens/1.xml
  def show
    @access_token = AccessToken.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @access_token }
    end
  end

  # GET /access_tokens/new
  # GET /access_tokens/new.xml
  def new
    @access_token = AccessToken.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @access_token }
    end
  end

  # GET /access_tokens/1/edit
  def edit
    @access_token = AccessToken.find(params[:id])
  end

  # POST /access_tokens
  # POST /access_tokens.xml
  def create
    require 'digest/sha1'
    
    @access_token = AccessToken.new
    @access_token.user_id = current_user.id
    @access_token.last_access = Time.now
    @access_token.token = Digest::SHA1.hexdigest Time.now.to_s
    @access_token.active = true
    
    respond_to do |format|
      if @access_token.save
        format.html { redirect_to(@access_token, :notice => 'Access token was successfully created.') }
        format.xml  { render :xml => @access_token, :status => :created, :location => @access_token }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @access_token.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /access_tokens/1
  # PUT /access_tokens/1.xml
  def update
    @access_token = AccessToken.find(params[:id])

    respond_to do |format|
      if @access_token.update_attributes(params[:access_token])
        format.html { redirect_to(@access_token, :notice => 'Access token was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @access_token.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /access_tokens/1
  # DELETE /access_tokens/1.xml
  def destroy
    @access_token = AccessToken.find(params[:id])
    @access_token.destroy

    respond_to do |format|
      format.html { redirect_to(access_tokens_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/access_tokens_helper.rb
module AccessTokensHelper
end

app/views/access_tokens/_form.html.erb
<%= form_for(@access_token) do |f| %>
  <% if @access_token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@access_token.errors.count, "error") %> prohibited this access_token from being saved:</h2>

      <ul>
      <% @access_token.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :last_access %><br />
    <%= f.datetime_select :last_access %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/access_tokens/edit.html.erb
<h1>Editing access_token</h1>

<%= render 'form' %>

<%= link_to 'Show', @access_token %> |
<%= link_to 'Back', access_tokens_path %>

app/views/access_tokens/index.html.erb
<h1>Listing access_tokens</h1>

<table>
  <tr>
    <th>User</th>
    <th>Token</th>
    <th>Active</th>
    <th>Last access</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @access_tokens.each do |access_token| %>
  <tr>
    <td><%= access_token.user.email %></td>
    <td><%= access_token.token %></td>
    <td><%= access_token.active %></td>
    <td><%= access_token.last_access %></td>
    <td><%= link_to 'Show', access_token %></td>
    <td><%= link_to 'Edit', edit_access_token_path(access_token) %></td>
    <td><%= link_to 'Destroy', access_token, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Access token', new_access_token_path %>

app/views/access_tokens/new.html.erb
<h1>New access_token</h1>

<%= form_for(@access_token) do |f| %>
  <% if @access_token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@access_token.errors.count, "error") %> prohibited this access_token from being saved:</h2>

      <ul>
      <% @access_token.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', access_tokens_path %>

app/views/access_tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @access_token.user_id %>
</p>

<p>
  <b>Token:</b>
  <%= @access_token.token %>
</p>

<p>
  <b>Active:</b>
  <%= @access_token.active %>
</p>

<p>
  <b>Last access:</b>
  <%= @access_token.last_access %>
</p>


<%= link_to 'Edit', edit_access_token_path(@access_token) %> |
<%= link_to 'Back', access_tokens_path %>