config/routes.rb
Opentrak::Application.routes.draw do
  
  resources :access_tokens
  
  devise_for :users

  resources :trackers
  resources :tags
  
  match 'track/:name' => 'trackers#track', :as => 'track_tracker'
  
  match 'api' => "api#post", :via => :post
  

  root :to => "trackers#blocked"

end

app/models/tracker.rb
# == Schema Information
# Schema version: 20110620211711
#
# Table name: trackers
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  count      :integer         default(0)
#  title      :string(255)
#  total_sent :integer         default(0)
#  created_at :datetime
#  updated_at :datetime
#  views      :integer         default(0)
#  source_id  :integer
#

class Tracker < ActiveRecord::Base
  acts_as_taggable
  has_many  :opens, :dependent => :destroy
  
  def increment(x=1)
    update_attributes(:count => count+x, :views => views+x)
  end
  
  def increment_sent(x=1)
    update_attributes(:total_sent => total_sent+x)
  end
  
  def open_rate
    if(total_sent>0)
      return (count.to_f / total_sent.to_f)*100
    else
      return 0.to_f
    end
  end
    
  def calculate_views
    x = 0
    opens.inject(0) do |a, b|
      x = a+b.count
    end
    
    return x
  end
  
  def self.find_or_create(tracker_name)
    @tracker = Tracker.find_by_name(tracker_name)
    
    if(@tracker)
      return @tracker
    else
     return Tracker.create!(:name => tracker_name, :count => 0)
    end
    
  end
  
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_filter :admin_user, :except => [:track, :blocked]
  require "pathname"
  
  # GET /trackers
  # GET /trackers.xml
  def index
    @trackers = Tracker.find(:all, :order => "id DESC").paginate(:page => params[:page], :per_page => 15)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @trackers }
    end
  end

  # GET /trackers/1
  # GET /trackers/1.xml
  def show
    @tracker = Tracker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tracker }
    end
  end

  # GET /trackers/new
  # GET /trackers/new.xml
  def new
    @tracker = Tracker.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tracker }
    end
  end

  # GET /trackers/1/edit
  def edit
    @tracker = Tracker.find(params[:id])
  end

  # POST /trackers
  # POST /trackers.xml
  def create    
    @tracker = Tracker.new(params[:tracker])

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to(@tracker, :notice => 'Tracker was successfully created.') }
        format.xml  { render :xml => @tracker, :status => :created, :location => @tracker }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tracker.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def track
    ip = env["HTTP_X_FORWARDED_FOR"]
    
    @tracker = Tracker.find_or_create(params[:name])
    
    # is there an existing one?
    @open = Open.find_by_tracker_id_and_ip(@tracker.id, ip)
    if(@open.nil?)
      @tracker.increment
      Open.create!(:tracker_id => @tracker.id, :ip => ip, :count => 1)
    else
      # increment the count of the Open
      @tracker.update_attribute(:views, @tracker.views+1)
      @open.update_attribute(:count, @open.count+1)
    end
    
    file = Rails.root.join("public/images/pixel.gif").to_s
    send_file file, :type => 'image/gif', :disposition => 'inline'
  end

  # PUT /trackers/1
  # PUT /trackers/1.xml
  def update
    @tracker = Tracker.find(params[:id])

    respond_to do |format|
      if @tracker.update_attributes(params[:tracker])
        format.html { redirect_to(@tracker, :notice => 'Tracker was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tracker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1
  # DELETE /trackers/1.xml
  def destroy
    @tracker = Tracker.find(params[:id])
    @tracker.destroy

    respond_to do |format|
      format.html { redirect_to(trackers_url) }
      format.xml  { head :ok }
    end
  end
  
  def blocked
    if(user_signed_in? && current_user.admin?)
      redirect_to trackers_path
    end
  end
  
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/trackers/_form.html.erb
<%= form_for(@tracker) do |f| %>
  <% if @tracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tracker.errors.count, "error") %> prohibited this tracker from being saved:</h2>

      <ul>
      <% @tracker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
	
  <div class="field">
    <%= f.label :source_id, "Source ID" %><br />
    <%= f.text_field :source_id %>
  </div>
  
  <div class="field">
    <%= f.label :total_sent %><br />
    <%= f.text_field :total_sent %>
  </div>

  <div class="field">
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trackers/_tag.html.erb
<%= link_to tag.name, tag_path(tag) %>&nbsp;

app/views/trackers/blocked.html.erb
<h1>No access</h1>

app/views/trackers/edit.html.erb
<h1>Editing tracker</h1>

<%= render 'form' %>

<%= link_to 'Show', @tracker %> |
<%= link_to 'Back', trackers_path %>

app/views/trackers/index.html.erb
<h1>Listing trackers</h1>

<table>
  <tr>
    <th>Name</th>
	<th>Title</th>
	<th>Age</th>
	<th>Last loaded</th>
    <th>Source ID</th>
	<th>Count</th>
	<th>Total views</th>
    <th>Open Rate</th>
    <th>Total sent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trackers.each do |tracker| %>
  <tr>
    <td><%= tracker.name %></td>
    <td><%= tracker.title %></td>
	<td><%= time_ago_in_words(tracker.created_at) %></td>
	<td><%= time_ago_in_words(tracker.opens.last.updated_at) %></td>
	<td><%= tracker.source_id %></td>
	<td><%= tracker.count %></td>
    <td><%= tracker.views %></td>
	<td><%= tracker.open_rate.round(3) %>%</td>
    <td><%= tracker.total_sent %></td>
    <td><%= link_to 'Show', tracker %></td>
    <td><%= link_to 'Edit', edit_tracker_path(tracker) %></td>
    <td><%= link_to 'Destroy', tracker, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= will_paginate %>

<p><strong>Keep on trackin'</strong></p>

app/views/trackers/new.html.erb
<h1>New tracker</h1>

<%= render 'form' %>

<%= link_to 'Back', trackers_path %>

app/views/trackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tracker.name %>
</p>

<p>
  <b>Count:</b>
  <%= @tracker.count %>
</p>

<p>
  <b>Total views:</b>
  <%= @tracker.views %>
</p>

<p>
  <b>Open rate:</b>
  <%= @tracker.open_rate.round(3) %>%
</p>

<p>
  <b>Title:</b>
  <%= @tracker.title %>
</p>

<p>
  <b>Source ID:</b>
  <%= @tracker.source_id %>
</p>

<p>
  <b>Total sent:</b>
  <%= @tracker.total_sent %>
</p>

<p>
  <b>Tags:</b>
  <%= render :partial => 'tag', :collection => @tracker.tags %>
</p>

<%= link_to 'Edit', edit_tracker_path(@tracker) %> |
<%= link_to 'Back', trackers_path %>

app/views/trackers/track.html.erb
<%= @tracker.count %>