config/routes.rb
Opentrak::Application.routes.draw do
  
  resources :access_tokens
  
  devise_for :users

  resources :trackers
  resources :tags
  
  match 'track/:name' => 'trackers#track', :as => 'track_tracker'
  
  match 'api' => "api#post", :via => :post
  

  root :to => "trackers#blocked"

end

app/views/layouts/_header.html.erb
<div id="user_nav">
  <div class="span-4 first">
      <%= link_to('Opentrak', trackers_path, :class => 'stencil large no-underline')%>
  </div>
  <div class="span-8">
	 &nbsp;
  </div>
  <div class="span-12 last">
		<% if user_signed_in? %>
			Hey there <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path%> | <%= link_to "API", access_tokens_path %>
		<% else %>
			<%= link_to "Log in", new_user_session_path %> | <%= link_to "Sign up", new_user_registration_path %> 
		<% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <!--[if lt IE 9]> <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= javascript_include_tag :defaults %>
  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Allerta+Stencil' %>
</head>
<body>
    <div class="full-width">
        <div class="container">
          <div class="span-24 last large" id="header">
            <%= render 'layouts/header' %>
          </div>
        </div>
    </div>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <div id="footer" class="span-24 last">
        <%= render 'layouts/footer' %>
      </div>
    </div>
</body>
</html>